import { Image_Uris } from "./Image-Uris";
import { Legalities } from "./Legalities";
import { Multiverse_Ids } from "./Multiverse-Ids";
import { Prices } from "./Prices";
import { Purchase_Uris } from "./Purchase_Uris";
import { Related_Uris } from "./Related_Uris";

export class Card{
    id:string = "";
    oracle_id!: string;
    multiverse_ids!: Multiverse_Ids;
    tcplayer_id!: number;
    cardmarket_id!: number;
    name: string = "";
    lang!: string;
    released_at!: string;
    uri!: string;
    scryfall_uri!: string;
    layout!: string;
    highres_image!: boolean;
    image_status!: string;
    image_uris!: Image_Uris;
    mana_cost!: string;
    cms!: number;
    type_line!: string;
    oracle_text!: string;
    colors!:string[];
    color_identity!: string[];
    keywords!: string[];
    legalities!: Legalities;
    games!: string[];
    reserved!: boolean;
    foil!: boolean;
    nonfoil!: boolean;
    finishes!: string[];
    oversized!: boolean;
    promo!: boolean;
    reprint!: boolean;
    variation!: boolean;
    set_id!: string;
    set!: string;
    set_name!: string;
    set_type!: string;
    set_uri!: string;
    set_search_uri!: string;
    scryfall_set_uri!: string;
    rulings_uri!: string;
    print_search_uri!: string;
    collector_number!: string;
    digital!: boolean;
    rarity!: string;
    flavor_text!: string;
    card_back_id!: string;
    artist!: string;
    artist_is!: string[];
    illustration_id!: string[];
    border_color!: string;
    frame!: string;
    full_art!: boolean;
    textless!: boolean;
    booster!: boolean;
    story_spotlight!: boolean;
    edhrec_rank!: number;
    penny_rank!: number;
    prices!: Prices;
    related_uris!: Related_Uris;
    purchase_uris!: Purchase_Uris;
}